"""drop_unused_tree_and_order_columns

Revision ID: 5df00cbf609c
Revises: 6c4c47b37e26
Create Date: 2026-03-30 15:14:10.250590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5df00cbf609c'
down_revision: Union[str, Sequence[str], None] = '6c4c47b37e26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'deposit')
    op.drop_column('trees', 'maintenance_required')
    op.drop_column('trees', 'deposit')
    op.drop_column('trees', 'available_quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trees', sa.Column('available_quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('trees', sa.Column('deposit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('trees', sa.Column('maintenance_required', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('deposit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
