"""drop_date_columns_from_orders

Revision ID: 6c4c47b37e26
Revises: a1b2c3d4e5f6
Create Date: 2026-03-28 09:37:29.948216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c4c47b37e26'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'start_date')
    op.drop_column('orders', 'delivery_slot')
    op.drop_column('orders', 'end_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('delivery_slot', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
