"""add_lat_lng_to_trees

Revision ID: 9b477a656f63
Revises: 
Create Date: 2026-03-27 13:37:16.941733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b477a656f63'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trees', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('trees', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trees', 'longitude')
    op.drop_column('trees', 'latitude')
    # ### end Alembic commands ###
