from sqlalchemy.orm import Session

from models import Tree

SEED_TREES = [
    {
        "name": "Alphonso Mango Tree",
        "type": "mango",
        "description": "The king of mangoes — Alphonso produces the sweetest, most aromatic mangoes. Perfect for home gardens and farms.",
        "price_per_day": 50.0,
        "price_per_month": 1200.0,
        "deposit": 500.0,
        "size": "Large (5-6 ft)",
        "maintenance_required": True,
        "image_url": "https://images.unsplash.com/photo-1553279768-865429fa0078?w=800",
        "available_quantity": 8,
    },
    {
        "name": "Dasheri Mango Tree",
        "type": "mango",
        "description": "Famous North Indian mango variety known for its incredible sweetness and fibre-free pulp.",
        "price_per_day": 45.0,
        "price_per_month": 1100.0,
        "deposit": 400.0,
        "size": "Large (5-6 ft)",
        "maintenance_required": True,
        "image_url": "https://images.unsplash.com/photo-1601493700631-2b16ec4b4716?w=800",
        "available_quantity": 6,
    },
    {
        "name": "Cavendish Banana Plant",
        "type": "banana",
        "description": "The world's most popular banana variety. Fast-growing, produces large bunches of sweet yellow bananas.",
        "price_per_day": 30.0,
        "price_per_month": 750.0,
        "deposit": 300.0,
        "size": "Large (6-8 ft)",
        "maintenance_required": True,
        "image_url": "https://images.unsplash.com/photo-1603833665858-e61d17a86224?w=800",
        "available_quantity": 10,
    },
    {
        "name": "Red Banana Plant",
        "type": "banana",
        "description": "Exotic red-skinned banana with creamy, slightly raspberry-flavoured flesh. A garden showpiece.",
        "price_per_day": 35.0,
        "price_per_month": 850.0,
        "deposit": 350.0,
        "size": "Medium (4-5 ft)",
        "maintenance_required": True,
        "image_url": "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=800",
        "available_quantity": 5,
    },
    {
        "name": "Nagpur Orange Tree",
        "type": "orange",
        "description": "India's most famous orange variety from Nagpur. Juicy, sweet, and fragrant — the classic citrus experience.",
        "price_per_day": 40.0,
        "price_per_month": 950.0,
        "deposit": 400.0,
        "size": "Medium (4-5 ft)",
        "maintenance_required": True,
        "image_url": "https://images.unsplash.com/photo-1582979512210-99b6a53386f9?w=800",
        "available_quantity": 7,
    },
    {
        "name": "Mosambi (Sweet Lime) Tree",
        "type": "orange",
        "description": "A popular citrus tree producing sweet, mild-flavoured limes. Great for juicing and fresh consumption.",
        "price_per_day": 35.0,
        "price_per_month": 850.0,
        "deposit": 350.0,
        "size": "Medium (3-4 ft)",
        "maintenance_required": False,
        "image_url": "https://images.unsplash.com/photo-1611080626919-7cf5a9dbab5b?w=800",
        "available_quantity": 6,
    },
    {
        "name": "Kagzi Lemon Tree",
        "type": "lemon",
        "description": "India's most widely grown lemon variety. Prolific bearer of juicy, tangy lemons throughout the year.",
        "price_per_day": 25.0,
        "price_per_month": 600.0,
        "deposit": 200.0,
        "size": "Medium (3-4 ft)",
        "maintenance_required": False,
        "image_url": "https://images.unsplash.com/photo-1622383563227-04401ab4e5ea?w=800",
        "available_quantity": 12,
    },
    {
        "name": "Tall Coconut Palm",
        "type": "coconut",
        "description": "Classic tropical coconut palm. Produces tender coconuts and adds instant tropical vibes to any space.",
        "price_per_day": 60.0,
        "price_per_month": 1500.0,
        "deposit": 600.0,
        "size": "Extra Large (7-8 ft)",
        "maintenance_required": True,
        "image_url": "https://images.unsplash.com/photo-1509937528035-ad76254b0356?w=800",
        "available_quantity": 4,
    },
    {
        "name": "Dwarf Coconut Palm",
        "type": "coconut",
        "description": "Compact coconut variety perfect for smaller spaces. Starts bearing fruit earlier than tall varieties.",
        "price_per_day": 55.0,
        "price_per_month": 1300.0,
        "deposit": 500.0,
        "size": "Large (5-6 ft)",
        "maintenance_required": True,
        "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800",
        "available_quantity": 5,
    },
    {
        "name": "Allahabad Safeda Guava",
        "type": "guava",
        "description": "Premium white-fleshed guava variety. Crispy, sweet, and packed with Vitamin C. A must-have fruit tree.",
        "price_per_day": 30.0,
        "price_per_month": 700.0,
        "deposit": 250.0,
        "size": "Medium (3-4 ft)",
        "maintenance_required": False,
        "image_url": "https://images.unsplash.com/photo-1536511132770-e5058c7e8c46?w=800",
        "available_quantity": 9,
    },
    {
        "name": "Pink Guava Tree",
        "type": "guava",
        "description": "Beautiful pink-fleshed guava with aromatic, sweet fruit. Excellent for eating fresh or making juice.",
        "price_per_day": 32.0,
        "price_per_month": 750.0,
        "deposit": 250.0,
        "size": "Medium (3-4 ft)",
        "maintenance_required": False,
        "image_url": "https://images.unsplash.com/photo-1612690669207-fed642192c40?w=800",
        "available_quantity": 7,
    },
    {
        "name": "Kashmiri Apple Tree",
        "type": "apple",
        "description": "Premium Kashmiri apple tree with delicious, crunchy red apples. Thrives in cooler climates.",
        "price_per_day": 55.0,
        "price_per_month": 1350.0,
        "deposit": 500.0,
        "size": "Large (5-6 ft)",
        "maintenance_required": True,
        "image_url": "https://images.unsplash.com/photo-1570913149827-d2ac84ab3f9a?w=800",
        "available_quantity": 4,
    },
    {
        "name": "Red Lady Papaya",
        "type": "papaya",
        "description": "High-yielding dwarf papaya variety. Produces sweet, red-fleshed fruits within months of planting.",
        "price_per_day": 20.0,
        "price_per_month": 500.0,
        "deposit": 150.0,
        "size": "Medium (4-5 ft)",
        "maintenance_required": False,
        "image_url": "https://images.unsplash.com/photo-1526318472351-c75fcf070305?w=800",
        "available_quantity": 10,
    },
    {
        "name": "Bhagwa Pomegranate",
        "type": "pomegranate",
        "description": "India's most popular pomegranate variety with deep red arils. Hardy tree that thrives in hot conditions.",
        "price_per_day": 40.0,
        "price_per_month": 950.0,
        "deposit": 400.0,
        "size": "Medium (3-4 ft)",
        "maintenance_required": False,
        "image_url": "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=800",
        "available_quantity": 6,
    },
    {
        "name": "Konkan Jackfruit Tree",
        "type": "jackfruit",
        "description": "Giant fruit tree producing massive, sweet jackfruits. A tropical favourite with delicious golden pods inside.",
        "price_per_day": 45.0,
        "price_per_month": 1100.0,
        "deposit": 500.0,
        "size": "Large (6-8 ft)",
        "maintenance_required": True,
        "image_url": "https://images.unsplash.com/photo-1528825871115-3581a5e0791d?w=800",
        "available_quantity": 3,
    },
    {
        "name": "Cricket Ball Chiku",
        "type": "chiku",
        "description": "Sweet, caramel-flavoured sapodilla fruit tree. The Cricket Ball variety produces large, round, extra-sweet fruits.",
        "price_per_day": 28.0,
        "price_per_month": 680.0,
        "deposit": 250.0,
        "size": "Medium (3-4 ft)",
        "maintenance_required": False,
        "image_url": "https://images.unsplash.com/photo-1478145046317-39f10e56b5e9?w=800",
        "available_quantity": 6,
    },
]


def seed_trees(db: Session) -> None:
    if db.query(Tree).count() > 0:
        return
    for data in SEED_TREES:
        db.add(Tree(**data))
    db.commit()
