from sqlalchemy.orm import Session

from models import Tree

SEED_TREES = [
    {
        "name": "Alphonso Mango Tree",
        "type": "mango",
        "variety": "Alphonso (Hapus)",
        "speciality": "King of mangoes — sweetest aroma, fibre-free golden pulp, GI tagged Ratnagiri origin",
        "description": "Premium Alphonso mango tree grafted from certified Ratnagiri stock. Produces the world-famous Hapus mangoes prized for their rich, creamy texture and unmatched sweetness.",
        "location": "Ratnagiri Farm",
        "city": "Ratnagiri",
        "state": "Maharashtra",
        "price_per_day": 50.0,
        "price_per_month": 1200.0,
        "price_per_season": 4500.0,
        "deposit": 500.0,
        "size": "Large (5-6 ft)",
        "min_quantity": 5,
        "available_quantity": 20,
        "maintenance_required": True,
        "image_url": "https://images.unsplash.com/photo-1553279768-865429fa0078?w=800",
    },
    {
        "name": "Dasheri Mango Tree",
        "type": "mango",
        "variety": "Dasheri",
        "speciality": "Famous Lucknow variety, incredibly sweet with zero fibre, perfect for aam ras",
        "description": "Authentic Dasheri mango tree from Lucknow nurseries. Known for its elongated shape, thin skin, and exceptionally sweet, fibre-free pulp that melts in your mouth.",
        "location": "Malihabad Orchards",
        "city": "Lucknow",
        "state": "Uttar Pradesh",
        "price_per_day": 45.0,
        "price_per_month": 1100.0,
        "price_per_season": 4000.0,
        "deposit": 400.0,
        "size": "Large (5-6 ft)",
        "min_quantity": 5,
        "available_quantity": 15,
        "maintenance_required": True,
        "image_url": "https://images.unsplash.com/photo-1601493700631-2b16ec4b4716?w=800",
    },
    {
        "name": "Langra Mango Tree",
        "type": "mango",
        "variety": "Langra",
        "speciality": "Stays green when ripe, strong sweet flavour, best for pickle and eating fresh",
        "description": "The iconic Langra mango tree from Varanasi. Unique for remaining green even when fully ripe, with a distinct sweet-tangy taste loved across North India.",
        "location": "Varanasi Farms",
        "city": "Varanasi",
        "state": "Uttar Pradesh",
        "price_per_day": 40.0,
        "price_per_month": 950.0,
        "price_per_season": 3500.0,
        "deposit": 350.0,
        "size": "Large (6-8 ft)",
        "min_quantity": 3,
        "available_quantity": 12,
        "maintenance_required": True,
        "image_url": "https://images.unsplash.com/photo-1591073113125-e46713c829ed?w=800",
    },
    {
        "name": "Cavendish Banana Plant",
        "type": "banana",
        "variety": "Grand Naine (Cavendish)",
        "speciality": "World's most popular banana, high yield, sweet and creamy, export quality",
        "description": "High-yield Cavendish banana plant producing large bunches of uniformly sweet, creamy yellow bananas. Ideal for commercial and home garden setups.",
        "location": "Jalgaon Banana Belt",
        "city": "Jalgaon",
        "state": "Maharashtra",
        "price_per_day": 30.0,
        "price_per_month": 750.0,
        "price_per_season": 2800.0,
        "deposit": 300.0,
        "size": "Large (6-8 ft)",
        "min_quantity": 10,
        "available_quantity": 50,
        "maintenance_required": True,
        "image_url": "https://images.unsplash.com/photo-1603833665858-e61d17a86224?w=800",
    },
    {
        "name": "Red Banana Plant",
        "type": "banana",
        "variety": "Red Dacca",
        "speciality": "Exotic red skin, creamy raspberry-flavoured flesh, rich in potassium and beta-carotene",
        "description": "Exotic red-skinned banana plant producing sweet fruits with a subtle raspberry undertone. A striking garden showpiece that also delivers a unique flavour experience.",
        "location": "Theni Hills",
        "city": "Theni",
        "state": "Tamil Nadu",
        "price_per_day": 35.0,
        "price_per_month": 850.0,
        "price_per_season": 3200.0,
        "deposit": 350.0,
        "size": "Medium (4-5 ft)",
        "min_quantity": 5,
        "available_quantity": 20,
        "maintenance_required": True,
        "image_url": "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=800",
    },
    {
        "name": "Nagpur Orange Tree",
        "type": "orange",
        "variety": "Nagpur Santra",
        "speciality": "India's most famous orange, GI tagged, juicy and sweet, peak season Dec–Mar",
        "description": "The iconic Nagpur Santra tree — India's premier orange variety. Produces bright, juicy oranges with the perfect sweet-tangy balance, ideal for juicing and fresh eating.",
        "location": "Katol Road Orchards",
        "city": "Nagpur",
        "state": "Maharashtra",
        "price_per_day": 40.0,
        "price_per_month": 950.0,
        "price_per_season": 3500.0,
        "deposit": 400.0,
        "size": "Medium (4-5 ft)",
        "min_quantity": 5,
        "available_quantity": 25,
        "maintenance_required": True,
        "image_url": "https://images.unsplash.com/photo-1582979512210-99b6a53386f9?w=800",
    },
    {
        "name": "Kagzi Lemon Tree",
        "type": "lemon",
        "variety": "Kagzi Nimbu",
        "speciality": "Year-round bearer, highly aromatic, thin skin with maximum juice content",
        "description": "India's most widely grown lemon variety. Prolific bearer producing juicy, tangy lemons throughout the year. Compact tree perfect for home gardens and commercial farms.",
        "location": "Nellore Farms",
        "city": "Nellore",
        "state": "Andhra Pradesh",
        "price_per_day": 25.0,
        "price_per_month": 600.0,
        "price_per_season": 2200.0,
        "deposit": 200.0,
        "size": "Medium (3-4 ft)",
        "min_quantity": 5,
        "available_quantity": 30,
        "maintenance_required": False,
        "image_url": "https://images.unsplash.com/photo-1622383563227-04401ab4e5ea?w=800",
    },
    {
        "name": "Tall Coconut Palm",
        "type": "coconut",
        "variety": "West Coast Tall",
        "speciality": "Hardy variety, produces 80-100 coconuts/year, drought tolerant, 60+ year lifespan",
        "description": "Classic West Coast Tall coconut palm known for its hardiness and high yield. Produces tender coconuts ideal for water and copra. Instant tropical garden transformation.",
        "location": "Konkan Coast Farm",
        "city": "Ratnagiri",
        "state": "Maharashtra",
        "price_per_day": 60.0,
        "price_per_month": 1500.0,
        "price_per_season": 5500.0,
        "deposit": 600.0,
        "size": "Extra Large (7-8 ft)",
        "min_quantity": 3,
        "available_quantity": 10,
        "maintenance_required": True,
        "image_url": "https://images.unsplash.com/photo-1509937528035-ad76254b0356?w=800",
    },
    {
        "name": "Allahabad Safeda Guava",
        "type": "guava",
        "variety": "Allahabad Safeda",
        "speciality": "Premium white-fleshed guava, crispy and aromatic, highest Vitamin C among fruits",
        "description": "India's finest guava variety with white, crispy, aromatic flesh. Each fruit weighs 200-250g. Extremely high in Vitamin C — more than any citrus fruit.",
        "location": "Prayagraj Nursery",
        "city": "Prayagraj",
        "state": "Uttar Pradesh",
        "price_per_day": 30.0,
        "price_per_month": 700.0,
        "price_per_season": 2600.0,
        "deposit": 250.0,
        "size": "Medium (3-4 ft)",
        "min_quantity": 5,
        "available_quantity": 25,
        "maintenance_required": False,
        "image_url": "https://images.unsplash.com/photo-1536511132770-e5058c7e8c46?w=800",
    },
    {
        "name": "Kashmiri Apple Tree",
        "type": "apple",
        "variety": "Red Delicious",
        "speciality": "Premium Kashmiri apple, deep red skin, crunchy and sweet, grows at 5000+ ft altitude",
        "description": "Authentic Kashmiri Red Delicious apple tree grown at high altitude for the perfect sweetness. Produces large, crunchy, deep-red apples with a distinctive elongated shape.",
        "location": "Shopian Valley Farm",
        "city": "Shopian",
        "state": "Jammu & Kashmir",
        "price_per_day": 55.0,
        "price_per_month": 1350.0,
        "price_per_season": 5000.0,
        "deposit": 500.0,
        "size": "Large (5-6 ft)",
        "min_quantity": 3,
        "available_quantity": 8,
        "maintenance_required": True,
        "image_url": "https://images.unsplash.com/photo-1570913149827-d2ac84ab3f9a?w=800",
    },
    {
        "name": "Red Lady Papaya",
        "type": "papaya",
        "variety": "Red Lady (Taiwan 786)",
        "speciality": "Dwarf hybrid, fruits in 8 months, sweet red flesh, tolerant to papaya ring spot virus",
        "description": "High-yielding dwarf papaya variety producing sweet, red-fleshed fruits within 8 months of planting. Virus-resistant hybrid ideal for year-round production.",
        "location": "Pune Agri Park",
        "city": "Pune",
        "state": "Maharashtra",
        "price_per_day": 20.0,
        "price_per_month": 500.0,
        "price_per_season": 1800.0,
        "deposit": 150.0,
        "size": "Medium (4-5 ft)",
        "min_quantity": 10,
        "available_quantity": 40,
        "maintenance_required": False,
        "image_url": "https://images.unsplash.com/photo-1526318472351-c75fcf070305?w=800",
    },
    {
        "name": "Bhagwa Pomegranate",
        "type": "pomegranate",
        "variety": "Bhagwa (Sinduri)",
        "speciality": "Deep red arils, soft seeds, 28+ Brix sweetness, drought-hardy, export-grade",
        "description": "India's most popular pomegranate variety with striking deep-red arils and soft seeds. Extremely sweet (28+ Brix), drought-tolerant, and perfect for hot, arid climates.",
        "location": "Solapur Farms",
        "city": "Solapur",
        "state": "Maharashtra",
        "price_per_day": 40.0,
        "price_per_month": 950.0,
        "price_per_season": 3600.0,
        "deposit": 400.0,
        "size": "Medium (3-4 ft)",
        "min_quantity": 5,
        "available_quantity": 18,
        "maintenance_required": False,
        "image_url": "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=800",
    },
    {
        "name": "Konkan Jackfruit Tree",
        "type": "jackfruit",
        "variety": "Konkan Prolific",
        "speciality": "Giant tropical fruit, sweet golden pods, each fruit up to 20 kg, wood also valuable",
        "description": "Prolific jackfruit variety from the Konkan coast producing massive, sweet fruits with golden pods. Each tree yields 50-80 fruits per season. The world's largest tree-borne fruit.",
        "location": "Sindhudurg Coastal Farm",
        "city": "Sindhudurg",
        "state": "Maharashtra",
        "price_per_day": 45.0,
        "price_per_month": 1100.0,
        "price_per_season": 4000.0,
        "deposit": 500.0,
        "size": "Large (6-8 ft)",
        "min_quantity": 2,
        "available_quantity": 8,
        "maintenance_required": True,
        "image_url": "https://images.unsplash.com/photo-1528825871115-3581a5e0791d?w=800",
    },
    {
        "name": "Cricket Ball Chiku",
        "type": "chiku",
        "variety": "Cricket Ball (Kalipatti)",
        "speciality": "Extra-large round fruits, caramel-sweet flavour, grainy texture, bears fruit year-round",
        "description": "Premium sapodilla variety producing large, round fruits with sweet, caramel-like flavour. Bears fruit multiple times a year. Named 'Cricket Ball' for its distinctive round shape.",
        "location": "Valsad Orchards",
        "city": "Valsad",
        "state": "Gujarat",
        "price_per_day": 28.0,
        "price_per_month": 680.0,
        "price_per_season": 2500.0,
        "deposit": 250.0,
        "size": "Medium (3-4 ft)",
        "min_quantity": 5,
        "available_quantity": 15,
        "maintenance_required": False,
        "image_url": "https://images.unsplash.com/photo-1478145046317-39f10e56b5e9?w=800",
    },
    {
        "name": "Kesar Mango Tree",
        "type": "mango",
        "variety": "Kesar (Gir Kesar)",
        "speciality": "GI tagged Junagadh variety, saffron-coloured pulp, intense aroma, Queen of Mangoes",
        "description": "The famed Gir Kesar mango tree producing saffron-coloured, intensely aromatic mangoes. GI tagged from Junagadh, known as the Queen of Mangoes for its royal flavour.",
        "location": "Gir Somnath Farm",
        "city": "Junagadh",
        "state": "Gujarat",
        "price_per_day": 48.0,
        "price_per_month": 1150.0,
        "price_per_season": 4200.0,
        "deposit": 450.0,
        "size": "Large (5-6 ft)",
        "min_quantity": 5,
        "available_quantity": 18,
        "maintenance_required": True,
        "image_url": "https://images.unsplash.com/photo-1563114773-84221bd62daa?w=800",
    },
    {
        "name": "Mosambi Sweet Lime Tree",
        "type": "orange",
        "variety": "Mosambi (Sweet Lime)",
        "speciality": "Mild sweet flavour, low acidity, favourite for fresh juice, medicinal properties",
        "description": "Popular sweet lime tree producing mild, sweet citrus fruits. Low acidity makes it perfect for fresh juice. Widely cultivated across Central India for commercial juicing.",
        "location": "Akola Citrus Belt",
        "city": "Akola",
        "state": "Maharashtra",
        "price_per_day": 35.0,
        "price_per_month": 850.0,
        "price_per_season": 3200.0,
        "deposit": 350.0,
        "size": "Medium (3-4 ft)",
        "min_quantity": 5,
        "available_quantity": 20,
        "maintenance_required": False,
        "image_url": "https://images.unsplash.com/photo-1611080626919-7cf5a9dbab5b?w=800",
    },
]


def seed_trees(db: Session) -> None:
    if db.query(Tree).count() > 0:
        return
    for data in SEED_TREES:
        db.add(Tree(**data))
    db.commit()
