from sqlalchemy.orm import Session

from models import Tree

SEED_TREES = [
    {
        "name": "Fiddle Leaf Fig",
        "type": "indoor",
        "description": "A stunning indoor statement plant with large, violin-shaped leaves. Perfect for living rooms and offices. Thrives in bright, indirect light.",
        "price_per_day": 15.0,
        "price_per_month": 350.0,
        "deposit": 100.0,
        "size": "Large (5-6 ft)",
        "maintenance_required": True,
        "image_url": "https://images.unsplash.com/photo-1459411552884-841db9b3cc2a?w=800",
        "available_quantity": 5,
    },
    {
        "name": "Monstera Deliciosa",
        "type": "indoor",
        "description": "The iconic Swiss Cheese Plant with its unique fenestrated leaves. A tropical beauty that brings life to any interior space.",
        "price_per_day": 12.0,
        "price_per_month": 280.0,
        "deposit": 80.0,
        "size": "Medium (3-4 ft)",
        "maintenance_required": True,
        "image_url": "https://images.unsplash.com/photo-1614594975525-e45190c55d0b?w=800",
        "available_quantity": 8,
    },
    {
        "name": "Japanese Maple",
        "type": "outdoor",
        "description": "Elegant ornamental tree with stunning red foliage. Ideal for garden landscaping, patios, and outdoor events.",
        "price_per_day": 25.0,
        "price_per_month": 600.0,
        "deposit": 200.0,
        "size": "Large (6-8 ft)",
        "maintenance_required": False,
        "image_url": "https://images.unsplash.com/photo-1477511801984-4ad318ed9846?w=800",
        "available_quantity": 3,
    },
    {
        "name": "Bonsai Pine",
        "type": "bonsai",
        "description": "A carefully cultivated miniature pine bonsai. Perfect for desks, shelves, or as a centerpiece. A living work of art.",
        "price_per_day": 10.0,
        "price_per_month": 250.0,
        "deposit": 150.0,
        "size": "Small (1-2 ft)",
        "maintenance_required": True,
        "image_url": "https://images.unsplash.com/photo-1567748157439-651aca2ff064?w=800",
        "available_quantity": 6,
    },
    {
        "name": "Cherry Blossom",
        "type": "decorative",
        "description": "Beautiful artificial cherry blossom tree for events and weddings. Realistic pink blossoms create a magical ambiance.",
        "price_per_day": 40.0,
        "price_per_month": 900.0,
        "deposit": 300.0,
        "size": "Large (7-8 ft)",
        "maintenance_required": False,
        "image_url": "https://images.unsplash.com/photo-1522383225653-ed111181a951?w=800",
        "available_quantity": 4,
    },
    {
        "name": "Olive Tree",
        "type": "outdoor",
        "description": "Mediterranean olive tree in a beautiful ceramic pot. Hardy and drought-tolerant. Perfect for patios and terraces.",
        "price_per_day": 20.0,
        "price_per_month": 480.0,
        "deposit": 150.0,
        "size": "Medium (4-5 ft)",
        "maintenance_required": False,
        "image_url": "https://images.unsplash.com/photo-1564429238961-5a3e452115d9?w=800",
        "available_quantity": 5,
    },
    {
        "name": "Snake Plant",
        "type": "indoor",
        "description": "Low-maintenance air-purifying champion. Thrives in any lighting condition. Perfect for beginners and busy offices.",
        "price_per_day": 8.0,
        "price_per_month": 180.0,
        "deposit": 50.0,
        "size": "Medium (2-3 ft)",
        "maintenance_required": False,
        "image_url": "https://images.unsplash.com/photo-1593482892540-d0e6945cdd24?w=800",
        "available_quantity": 12,
    },
    {
        "name": "Juniper Bonsai",
        "type": "bonsai",
        "description": "Classic juniper bonsai with a beautifully shaped trunk. One of the most popular bonsai species, symbolizing strength and longevity.",
        "price_per_day": 12.0,
        "price_per_month": 280.0,
        "deposit": 120.0,
        "size": "Small (1 ft)",
        "maintenance_required": True,
        "image_url": "https://images.unsplash.com/photo-1599598177991-ec67b5c37318?w=800",
        "available_quantity": 4,
    },
    {
        "name": "Palm Tree",
        "type": "decorative",
        "description": "Tropical areca palm that instantly transforms any space into a resort. Great for events, lobbies, and photo shoots.",
        "price_per_day": 30.0,
        "price_per_month": 700.0,
        "deposit": 200.0,
        "size": "Large (6-7 ft)",
        "maintenance_required": True,
        "image_url": "https://images.unsplash.com/photo-1509937528035-ad76254b0356?w=800",
        "available_quantity": 6,
    },
    {
        "name": "Rubber Plant",
        "type": "indoor",
        "description": "Bold, glossy-leaved indoor tree that adds a touch of drama. Easy to care for and great at purifying indoor air.",
        "price_per_day": 10.0,
        "price_per_month": 230.0,
        "deposit": 60.0,
        "size": "Medium (3-4 ft)",
        "maintenance_required": False,
        "image_url": "https://images.unsplash.com/photo-1509423350716-97f9360b4e09?w=800",
        "available_quantity": 7,
    },
    {
        "name": "Lemon Tree",
        "type": "outdoor",
        "description": "Fragrant citrus tree with real lemons. Brightens up any outdoor space and provides fresh fruit. A delightful sensory experience.",
        "price_per_day": 18.0,
        "price_per_month": 420.0,
        "deposit": 120.0,
        "size": "Medium (4-5 ft)",
        "maintenance_required": True,
        "image_url": "https://images.unsplash.com/photo-1622383563227-04401ab4e5ea?w=800",
        "available_quantity": 4,
    },
    {
        "name": "Weeping Fig",
        "type": "indoor",
        "description": "Graceful indoor tree with delicate, arching branches and small green leaves. A timeless classic for home and office interiors.",
        "price_per_day": 14.0,
        "price_per_month": 320.0,
        "deposit": 90.0,
        "size": "Large (5-6 ft)",
        "maintenance_required": True,
        "image_url": "https://images.unsplash.com/photo-1463936575829-25148e1db1b8?w=800",
        "available_quantity": 5,
    },
]


def seed_trees(db: Session) -> None:
    if db.query(Tree).count() > 0:
        return
    for data in SEED_TREES:
        db.add(Tree(**data))
    db.commit()
